#!/usr/bin/env node
/**
 * Enlight ITSM — one-command deploy tool.
 *
 *   node deploy.mjs            interactive deploy wizard
 *   node deploy.mjs destroy    tear down the last deployment
 *   node deploy.mjs --generate-only   write config files but don't run Terraform
 *
 * Provisions a single VM (GCP / AWS / DigitalOcean) that runs the full Enlight
 * stack via Docker Compose: the app (built from source), PostgreSQL+pgvector,
 * and Redis. No prior infrastructure knowledge required.
 */

import readline from 'node:readline';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const STATE_FILE = path.join(__dirname, '.enlight-deploy.json');

// ── Pretty output ────────────────────────────────────────────────────────────
const c = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  cyan: '\x1b[36m', green: '\x1b[32m', yellow: '\x1b[33m', red: '\x1b[31m', blue: '\x1b[34m',
};
const color = (col, s) => `${c[col]}${s}${c.reset}`;
const log = (s = '') => console.log(s);
const ok = (s) => log(color('green', `✓ ${s}`));
const warn = (s) => log(color('yellow', `! ${s}`));
const err = (s) => log(color('red', `✗ ${s}`));

function banner() {
  log();
  log(color('cyan', '  ╔═══════════════════════════════════════════╗'));
  log(color('cyan', '  ║') + color('bold', '        Enlight ITSM — Deploy Tool         ') + color('cyan', '║'));
  log(color('cyan', '  ╚═══════════════════════════════════════════╝'));
  log(color('dim', '  Stand up a production instance in a few minutes.'));
  log();
}

// ── Prompt helpers ───────────────────────────────────────────────────────────
// A buffered line reader — works reliably for both interactive (TTY) and piped
// input (rl.question only reads the first piped line on recent Node versions).
function makeReader() {
  const rl = readline.createInterface({ input: process.stdin });
  const buf = [];
  const waiters = [];
  let closed = false;
  rl.on('line', (l) => { if (waiters.length) waiters.shift()(l); else buf.push(l); });
  rl.on('close', () => { closed = true; while (waiters.length) waiters.shift()(null); });
  return {
    next() {
      if (buf.length) return Promise.resolve(buf.shift());
      if (closed) return Promise.resolve(null);
      return new Promise((res) => waiters.push(res));
    },
    close() { rl.close(); },
  };
}
const reader = makeReader();
const rl = { close: () => reader.close() };
async function question(prompt) {
  process.stdout.write(prompt);
  const line = await reader.next();
  return line === null ? '' : line;
}

async function ask(label, { def = '', required = false, secret = false } = {}) {
  const hint = def ? color('dim', ` [${secret ? '••••' : def}]`) : (required ? color('dim', ' (required)') : color('dim', ' (optional)'));
  for (;;) {
    const a = (await question(`  ${label}${hint}: `)).trim();
    const val = a || def;
    if (required && !val) { err('  This value is required.'); continue; }
    return val;
  }
}

async function select(label, options) {
  log(`  ${color('bold', label)}`);
  options.forEach((o, i) => log(`    ${color('cyan', String(i + 1))}) ${o.label}`));
  for (;;) {
    const a = (await question(`  Choose ${color('dim', '[1-' + options.length + ']')}: `)).trim();
    const n = parseInt(a, 10);
    if (n >= 1 && n <= options.length) return options[n - 1].value;
    err('  Enter a number from the list.');
  }
}

async function confirm(label, def = true) {
  const a = (await question(`  ${label} ${color('dim', def ? '[Y/n]' : '[y/N]')}: `)).trim().toLowerCase();
  if (!a) return def;
  return a === 'y' || a === 'yes';
}

// ── Secret generation ────────────────────────────────────────────────────────
const randHex = (bytes) => crypto.randomBytes(bytes).toString('hex');
const randPass = () => crypto.randomBytes(18).toString('base64url'); // url-safe, no special chars

// ── .env builder ─────────────────────────────────────────────────────────────
function buildEnv(a) {
  const lines = [
    '# Generated by the Enlight deploy tool. Edit + re-run `docker compose up -d` to apply.',
    'NODE_ENV=production',
    'PORT=3000',
    '',
    '# Database + queue (compose service names)',
    `DATABASE_URL=postgresql://enlight:${a.pgPassword}@postgres:5432/enlight`,
    'REDIS_URL=redis://redis:6379',
    'POSTGRES_USER=enlight',
    `POSTGRES_PASSWORD=${a.pgPassword}`,
    'POSTGRES_DB=enlight',
    '',
    '# Secrets (auto-generated — keep private)',
    `JWT_SECRET=${a.jwtSecret}`,
    `SESSION_SECRET=${a.sessionSecret}`,
    `SECRETS_ENCRYPTION_KEY=${a.encKey}`,
    '',
    '# AI (the platform is also selectable in-app under Settings → AI Keys)',
    `ANTHROPIC_API_KEY=${a.anthropicKey}`,
  ];
  if (a.openaiKey) lines.push(`OPENAI_API_KEY=${a.openaiKey}`);
  if (a.voyageKey) lines.push(`VOYAGE_API_KEY=${a.voyageKey}`);
  lines.push('EMBEDDING_PROVIDER=voyage');
  lines.push('');
  lines.push('# Public URLs — used for email/portal/SSO links.');
  if (a.domain) {
    lines.push(`API_URL=https://${a.domain}`);
    lines.push(`WEB_URL=https://${a.domain}`);
  } else {
    lines.push('# No domain set — update these to your server URL for correct links:');
    lines.push('# API_URL=https://your-domain');
    lines.push('# WEB_URL=https://your-domain');
  }
  lines.push('');
  lines.push('# Licensing is disabled by default (pre-release).');
  lines.push('LICENSE_ENFORCEMENT=false');
  lines.push('');
  return lines.join('\n');
}

// ── tfvars builder ───────────────────────────────────────────────────────────
function tfvarLine(k, v) {
  if (Array.isArray(v)) return `${k} = [${v.map((x) => `"${x}"`).join(', ')}]`;
  if (typeof v === 'number') return `${k} = ${v}`;
  return `${k} = "${String(v).replace(/"/g, '\\"')}"`;
}
function buildTfvars(obj) {
  return Object.entries(obj).map(([k, v]) => tfvarLine(k, v)).join('\n') + '\n';
}

// ── Terraform runner ─────────────────────────────────────────────────────────
function hasTerraform() {
  const r = spawnSync('terraform', ['version'], { stdio: 'ignore' });
  return r.status === 0;
}
function runTf(dir, args) {
  return new Promise((res) => {
    const p = spawn('terraform', [`-chdir=${dir}`, ...args], { stdio: 'inherit' });
    p.on('close', (code) => res(code));
  });
}

// ── Cloud definitions ────────────────────────────────────────────────────────
const CLOUDS = {
  gcp: {
    label: 'Google Cloud Platform (Compute Engine)',
    dir: 'terraform/gcp',
    creds: 'Run `gcloud auth application-default login` and have a project ready.',
    async prompts() {
      const project_id   = await ask('GCP project ID', { required: true });
      const region       = await ask('Region', { def: 'us-central1' });
      const zone         = await ask('Zone', { def: 'us-central1-a' });
      const machine_type = await ask('Machine type', { def: 'e2-small' });
      return { project_id, region, zone, machine_type };
    },
  },
  aws: {
    label: 'Amazon Web Services (EC2)',
    dir: 'terraform/aws',
    creds: 'Configure AWS credentials (`aws configure` or AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY). A default VPC is required.',
    async prompts() {
      const region        = await ask('Region', { def: 'us-east-1' });
      const instance_type = await ask('Instance type', { def: 't3.small' });
      const key_name      = await ask('EC2 key pair name for SSH', {});
      return { region, instance_type, key_name };
    },
  },
  digitalocean: {
    label: 'DigitalOcean (Droplet)',
    dir: 'terraform/digitalocean',
    creds: 'You will paste a DigitalOcean API token (no other setup needed).',
    async prompts() {
      const do_token     = await ask('DigitalOcean API token', { required: true, secret: true });
      const region       = await ask('Region', { def: 'nyc1' });
      const droplet_size = await ask('Droplet size', { def: 's-1vcpu-2gb' });
      const fp           = await ask('SSH key fingerprint for access', {});
      const out = { do_token, region, droplet_size };
      if (fp) out.ssh_key_fingerprints = [fp];
      return out;
    },
  },
};

// ── Deploy flow ──────────────────────────────────────────────────────────────
async function deploy(generateOnly) {
  banner();

  const cloud = await select('Where would you like to deploy?', [
    { label: CLOUDS.gcp.label, value: 'gcp' },
    { label: CLOUDS.aws.label, value: 'aws' },
    { label: CLOUDS.digitalocean.label, value: 'digitalocean' },
  ]);
  const def = CLOUDS[cloud];
  log();
  log(color('dim', `  Credentials: ${def.creds}`));
  log();

  // ── App configuration ──
  log(color('bold', '  Application configuration'));
  const anthropicKey = await ask('Anthropic API key (Enter to set later in-app)', {});
  const more = await confirm('Add other API keys now (OpenAI, Voyage)?', false);
  let openaiKey = '', voyageKey = '';
  if (more) {
    openaiKey = await ask('OpenAI API key', {});
    voyageKey = await ask('Voyage API key (knowledge base embeddings)', {});
  }
  const domain = await ask('Domain name pointing at this server (optional)', {});
  log();

  // ── Cloud-specific ──
  log(color('bold', `  ${def.label} settings`));
  const cloudVars = await def.prompts();
  log();

  // ── Generate secrets + write files ──
  const app = {
    anthropicKey, openaiKey, voyageKey, domain,
    pgPassword: randPass(),
    jwtSecret: randHex(24),
    sessionSecret: randHex(24),
    encKey: randHex(32), // 64 hex chars = 32 bytes
  };
  const tfDir = path.join(__dirname, def.dir);
  fs.writeFileSync(path.join(tfDir, '.env'), buildEnv(app));
  fs.writeFileSync(path.join(tfDir, 'terraform.tfvars'), buildTfvars(cloudVars));
  ok(`Wrote ${def.dir}/.env and terraform.tfvars`);
  log(color('dim', '  Secrets were auto-generated. These files contain credentials — keep them private.'));
  log();

  fs.writeFileSync(STATE_FILE, JSON.stringify({ cloud, dir: def.dir }, null, 2));

  if (generateOnly) {
    ok('Generated config only (--generate-only). Run terraform yourself when ready:');
    log(color('dim', `    terraform -chdir=${def.dir} init && terraform -chdir=${def.dir} apply`));
    rl.close();
    return;
  }

  // ── Provision ──
  if (!hasTerraform()) {
    warn('Terraform is not installed — config files are ready, but I can\'t provision for you.');
    log(color('dim', '  Install Terraform: https://developer.hashicorp.com/terraform/install'));
    log(color('dim', `  Then run:  terraform -chdir=${def.dir} init && terraform -chdir=${def.dir} apply`));
    rl.close();
    return;
  }

  const go = await confirm(`Provision now on ${def.label}? This creates real cloud resources.`, true);
  if (!go) { warn('Skipped provisioning. Config files are ready when you are.'); rl.close(); return; }
  rl.close();

  log();
  log(color('blue', '  → terraform init'));
  if (await runTf(def.dir, ['init', '-input=false']) !== 0) { err('terraform init failed.'); process.exit(1); }

  log();
  log(color('blue', '  → terraform apply'));
  if (await runTf(def.dir, ['apply', '-input=false', '-auto-approve']) !== 0) { err('terraform apply failed.'); process.exit(1); }

  // ── Show outputs ──
  log();
  const out = spawnSync('terraform', [`-chdir=${def.dir}`, 'output', '-json'], { encoding: 'utf8' });
  let url = '';
  try {
    const o = JSON.parse(out.stdout || '{}');
    url = o.url?.value ?? '';
    log(color('green', color('bold', '  🎉 Deployed!')));
    if (o.public_ip) log(`     Public IP : ${color('bold', o.public_ip.value)}`);
    if (url)         log(`     URL       : ${color('bold', url)}`);
    if (o.ssh)       log(`     SSH       : ${color('dim', o.ssh.value)}`);
  } catch { /* ignore */ }

  log();
  log(color('bold', '  Next steps'));
  log(`    1. Wait ~3–5 min for the first build to finish on the VM.`);
  log(`    2. Open ${url || 'the URL above'} — the setup wizard will create your org + admin.`);
  if (!domain) log(color('dim', `    3. For correct email/portal links, set WEB_URL/API_URL in /opt/enlight/.env to your server URL and run \`docker compose up -d\`.`));
  log();
  log(color('dim', `  Tear down later with:  node deploy.mjs destroy`));
  log();
}

// ── Destroy flow ─────────────────────────────────────────────────────────────
async function destroy() {
  banner();
  if (!fs.existsSync(STATE_FILE)) { err('No previous deployment found (.enlight-deploy.json missing).'); rl.close(); return; }
  const { cloud, dir } = JSON.parse(fs.readFileSync(STATE_FILE, 'utf8'));
  warn(`This will DESTROY the ${CLOUDS[cloud]?.label ?? cloud} deployment and all its data.`);
  const sure = await confirm('Are you sure?', false);
  rl.close();
  if (!sure) { log('  Cancelled.'); return; }
  if (!hasTerraform()) { err('Terraform not installed.'); return; }
  await runTf(dir, ['destroy', '-input=false', '-auto-approve']);
  ok('Destroyed.');
}

// ── Entry ────────────────────────────────────────────────────────────────────
const cmd = process.argv[2];
const generateOnly = process.argv.includes('--generate-only');
try {
  if (cmd === 'destroy') await destroy();
  else await deploy(generateOnly);
} catch (e) {
  err(e?.message ?? String(e));
  process.exit(1);
}
