#!/usr/bin/env node
/**
 * Enlight ITSM — one-command deploy tool.
 *
 *   node deploy.mjs            interactive deploy wizard
 *   node deploy.mjs destroy    tear down the last deployment
 *   node deploy.mjs --generate-only   write config files but don't run Terraform
 *
 * Provisions a single VM (GCP / AWS / DigitalOcean) that runs the full Enlight
 * stack via Docker Compose: the app (built from source), PostgreSQL+pgvector,
 * and Redis. No prior infrastructure knowledge required.
 */

import readline from 'node:readline';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const STATE_FILE = path.join(__dirname, '.enlight-deploy.json');

// ── Pretty output ────────────────────────────────────────────────────────────
const c = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  cyan: '\x1b[36m', green: '\x1b[32m', yellow: '\x1b[33m', red: '\x1b[31m', blue: '\x1b[34m',
};
const color = (col, s) => `${c[col]}${s}${c.reset}`;
const log = (s = '') => console.log(s);
const ok = (s) => log(color('green', `✓ ${s}`));
const warn = (s) => log(color('yellow', `! ${s}`));
const err = (s) => log(color('red', `✗ ${s}`));

function banner() {
  log();
  log(color('cyan', '  ╔═══════════════════════════════════════════╗'));
  log(color('cyan', '  ║') + color('bold', '        Enlight ITSM — Deploy Tool         ') + color('cyan', '║'));
  log(color('cyan', '  ╚═══════════════════════════════════════════╝'));
  log(color('dim', '  Stand up a production instance in a few minutes.'));
  log();
}

// ── Prompt helpers ───────────────────────────────────────────────────────────
// A buffered line reader — works reliably for both interactive (TTY) and piped
// input (rl.question only reads the first piped line on recent Node versions).
function makeReader() {
  const rl = readline.createInterface({ input: process.stdin });
  const buf = [];
  const waiters = [];
  let closed = false;
  rl.on('line', (l) => { if (waiters.length) waiters.shift()(l); else buf.push(l); });
  rl.on('close', () => { closed = true; while (waiters.length) waiters.shift()(null); });
  return {
    next() {
      if (buf.length) return Promise.resolve(buf.shift());
      if (closed) return Promise.resolve(null);
      return new Promise((res) => waiters.push(res));
    },
    close() { rl.close(); },
  };
}
const reader = makeReader();
const rl = { close: () => reader.close() };
async function question(prompt) {
  process.stdout.write(prompt);
  const line = await reader.next();
  return line === null ? '' : line;
}

async function ask(label, { def = '', required = false, secret = false } = {}) {
  const hint = def ? color('dim', ` [${secret ? '••••' : def}]`) : (required ? color('dim', ' (required)') : color('dim', ' (optional)'));
  for (;;) {
    const a = (await question(`  ${label}${hint}: `)).trim();
    const val = a || def;
    if (required && !val) { err('  This value is required.'); continue; }
    return val;
  }
}

async function select(label, options) {
  log(`  ${color('bold', label)}`);
  options.forEach((o, i) => {
    log(`    ${color('cyan', String(i + 1))}) ${o.label}`);
    if (o.desc) log(`       ${color('dim', o.desc)}`);
  });
  for (;;) {
    const a = (await question(`  Choose ${color('dim', '[1-' + options.length + ']')}: `)).trim();
    const n = parseInt(a, 10);
    if (n >= 1 && n <= options.length) return options[n - 1].value;
    err('  Enter a number from the list.');
  }
}

async function confirm(label, def = true) {
  const a = (await question(`  ${label} ${color('dim', def ? '[Y/n]' : '[y/N]')}: `)).trim().toLowerCase();
  if (!a) return def;
  return a === 'y' || a === 'yes';
}

// Print dimmed, indented guidance (a string or an array of lines).
function info(text) {
  for (const line of (Array.isArray(text) ? text : [text])) log(color('dim', `  ${line}`));
}

// A numbered step header.
function section(n, total, title) {
  log();
  log(color('cyan', `  ─── Step ${n}/${total} · ${color('bold', title)}${c.reset}${c.cyan} ───`));
  log();
}

// A "Requirements:" block listing what a step needs.
function reqs(items) {
  log(color('yellow', '  What you need for this step:'));
  for (const it of items) log(`    ${color('yellow', '•')} ${color('dim', it)}`);
  log();
}

// ── Secret generation ────────────────────────────────────────────────────────
const randHex = (bytes) => crypto.randomBytes(bytes).toString('hex');
const randPass = () => crypto.randomBytes(18).toString('base64url'); // url-safe, no special chars

// ── .env builder ─────────────────────────────────────────────────────────────
function buildEnv(a) {
  const lines = [
    '# Generated by the Enlight deploy tool. Edit + re-run `docker compose up -d` to apply.',
    'NODE_ENV=production',
    'PORT=3000',
    '',
    '# Database + queue (compose service names)',
    `DATABASE_URL=postgresql://enlight:${a.pgPassword}@postgres:5432/enlight`,
    'REDIS_URL=redis://redis:6379',
    'POSTGRES_USER=enlight',
    `POSTGRES_PASSWORD=${a.pgPassword}`,
    'POSTGRES_DB=enlight',
    '',
    '# Secrets (auto-generated — keep private)',
    `JWT_SECRET=${a.jwtSecret}`,
    `SESSION_SECRET=${a.sessionSecret}`,
    `SECRETS_ENCRYPTION_KEY=${a.encKey}`,
    '',
    '# GitHub token — used to clone the app repo if it is private, and to power',
    '# the in-app update check (Settings → Updates) for private repos.',
    `GITHUB_TOKEN=${a.githubToken || ''}`,
    '',
    '# AI platform (default for new orgs; also changeable in Settings → AI Keys)',
    `AI_PROVIDER=${a.aiProvider}`,
    `ANTHROPIC_API_KEY=${a.anthropicKey || ''}`,
  ];
  if (a.openaiKey) lines.push(`OPENAI_API_KEY=${a.openaiKey}`);
  lines.push('');
  lines.push('# Knowledge base embeddings');
  lines.push(`EMBEDDING_PROVIDER=${a.embeddingProvider}`);
  if (a.voyageKey) lines.push(`VOYAGE_API_KEY=${a.voyageKey}`);
  lines.push('');
  lines.push('# Reverse proxy / TLS (read by Caddy). A hostname enables automatic HTTPS;');
  lines.push('# ":80" serves plain HTTP.');
  lines.push(`SITE_ADDRESS=${a.domain || ':80'}`);
  lines.push('');
  lines.push('# Public URLs — used for email/portal/SSO links.');
  if (a.domain) {
    lines.push(`API_URL=https://${a.domain}`);
    lines.push(`WEB_URL=https://${a.domain}`);
  } else {
    lines.push('# No domain set — update these (and SITE_ADDRESS above) once you add one:');
    lines.push('# API_URL=https://your-domain');
    lines.push('# WEB_URL=https://your-domain');
  }
  lines.push('');
  lines.push('# Licensing is disabled by default (pre-release).');
  lines.push('LICENSE_ENFORCEMENT=false');
  lines.push('');
  return lines.join('\n');
}

// ── Deployment state / resume ────────────────────────────────────────────────
function saveState(obj) {
  fs.writeFileSync(STATE_FILE, JSON.stringify(obj, null, 2));
}

/** Returns saved deployment state if a previous run left config behind, else null. */
function existingDeployment() {
  if (!fs.existsSync(STATE_FILE)) return null;
  let state;
  try { state = JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')); } catch { return null; }
  if (!state?.dir) return null;
  const dir = path.join(__dirname, state.dir);
  const hasConfig = fs.existsSync(path.join(dir, '.env')) && fs.existsSync(path.join(dir, 'terraform.tfvars'));
  if (!hasConfig) return null;
  return { ...state, provisioned: isProvisioned(state.dir) };
}

/** True if Terraform state for this dir contains created resources. */
function isProvisioned(relDir) {
  const tfstate = path.join(__dirname, relDir, 'terraform.tfstate');
  if (!fs.existsSync(tfstate)) return false;
  try {
    const s = JSON.parse(fs.readFileSync(tfstate, 'utf8'));
    return Array.isArray(s.resources) && s.resources.length > 0;
  } catch { return false; }
}

/** Reads the configured domain (SITE_ADDRESS) back out of a generated .env. */
function readDomainFromEnv(relDir) {
  try {
    const env = fs.readFileSync(path.join(__dirname, relDir, '.env'), 'utf8');
    const m = env.match(/^SITE_ADDRESS=(.+)$/m);
    const v = m?.[1]?.trim();
    return v && v !== ':80' ? v : '';
  } catch { return ''; }
}

// ── tfvars builder ───────────────────────────────────────────────────────────
function tfvarLine(k, v) {
  if (Array.isArray(v)) return `${k} = [${v.map((x) => `"${x}"`).join(', ')}]`;
  if (typeof v === 'number') return `${k} = ${v}`;
  return `${k} = "${String(v).replace(/"/g, '\\"')}"`;
}
function buildTfvars(obj) {
  return Object.entries(obj).map(([k, v]) => tfvarLine(k, v)).join('\n') + '\n';
}

// ── Terraform: resolve, install, run ─────────────────────────────────────────
// The binary the wizard uses. Set to the system `terraform` or a locally
// downloaded one in ./bin.
let TERRAFORM = 'terraform';
const TF_FALLBACK_VERSION = '1.9.8';
const localTfPath = () =>
  path.join(__dirname, 'bin', process.platform === 'win32' ? 'terraform.exe' : 'terraform');

function works(bin) {
  return spawnSync(bin, ['version'], { stdio: 'ignore' }).status === 0;
}

/** Find a usable Terraform (system PATH, then ./bin). Returns the path or null. */
function resolveTerraform() {
  if (works('terraform')) return 'terraform';
  const local = localTfPath();
  if (fs.existsSync(local) && works(local)) return local;
  return null;
}

/** Download + extract the official Terraform binary into ./bin. Sets TERRAFORM. */
async function installTerraform() {
  const os = { darwin: 'darwin', linux: 'linux', win32: 'windows' }[process.platform];
  const arch = { x64: 'amd64', arm64: 'arm64' }[process.arch];
  if (!os || !arch) throw new Error(`Unsupported platform ${process.platform}/${process.arch} — install Terraform manually.`);

  // Resolve the current version (fall back to a pinned one if the API is unreachable).
  let version = TF_FALLBACK_VERSION;
  try {
    const r = await fetch('https://checkpoint-api.hashicorp.com/v1/check/terraform', { signal: AbortSignal.timeout(8000) });
    const j = await r.json();
    if (j?.current_version) version = j.current_version;
  } catch { /* use fallback */ }

  const url = `https://releases.hashicorp.com/terraform/${version}/terraform_${version}_${os}_${arch}.zip`;
  const binDir = path.join(__dirname, 'bin');
  fs.mkdirSync(binDir, { recursive: true });
  const zipPath = path.join(binDir, 'terraform.zip');

  log(color('dim', `  Downloading Terraform ${version} (${os}/${arch})…`));
  const resp = await fetch(url, { signal: AbortSignal.timeout(180000) });
  if (!resp.ok) throw new Error(`Download failed (HTTP ${resp.status}) from ${url}`);
  fs.writeFileSync(zipPath, Buffer.from(await resp.arrayBuffer()));

  // Extract (the zip holds a single `terraform` binary). Try unzip, then bsdtar.
  let extracted = spawnSync('unzip', ['-o', zipPath, '-d', binDir], { stdio: 'ignore' }).status === 0;
  if (!extracted) extracted = spawnSync('tar', ['-xf', zipPath, '-C', binDir], { stdio: 'ignore' }).status === 0;
  fs.rmSync(zipPath, { force: true });
  if (!extracted) throw new Error('Could not unzip the download (need `unzip` or a zip-capable `tar`).');

  const bin = localTfPath();
  if (!fs.existsSync(bin)) throw new Error('Extraction succeeded but the terraform binary was not found.');
  fs.chmodSync(bin, 0o755);
  if (!works(bin)) throw new Error('The downloaded Terraform binary did not run.');
  TERRAFORM = bin;
  return version;
}

function runTf(dir, args) {
  return new Promise((res) => {
    const p = spawn(TERRAFORM, [`-chdir=${dir}`, ...args], { stdio: 'inherit' });
    p.on('close', (code) => res(code));
  });
}

// ── Cloud definitions ────────────────────────────────────────────────────────
const CLOUDS = {
  gcp: {
    label: 'Google Cloud Platform',
    menuDesc: 'Compute Engine VM · ~$13/mo (e2-small)',
    dir: 'terraform/gcp',
    credsLines: [
      'Before continuing, make sure you have:',
      '  • The gcloud CLI installed and authenticated for Terraform:',
      '      gcloud auth application-default login',
      '  • A GCP project — you\'ll need its Project ID (not the display name).',
    ],
    async prompts() {
      info(['Project ID: the unique ID in the GCP console top bar, e.g. my-project-123456.']);
      const project_id = await ask('GCP project ID', { required: true });
      info(['', 'Region / zone: where the VM runs. Defaults are fine — pick one near your users.']);
      const region = await ask('Region', { def: 'us-central1' });
      const zone   = await ask('Zone', { def: 'us-central1-a' });
      info(['', 'Machine type: e2-small (2 GB RAM) handles a small team. Use e2-medium for more headroom.']);
      const machine_type = await ask('Machine type', { def: 'e2-small' });
      return { project_id, region, zone, machine_type };
    },
  },
  aws: {
    label: 'Amazon Web Services',
    menuDesc: 'EC2 instance · ~$15/mo (t3.small)',
    dir: 'terraform/aws',
    credsLines: [
      'Before continuing, make sure you have:',
      '  • AWS credentials configured — `aws configure`, or the env vars',
      '      AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.',
      '  • A default VPC in your chosen region (most accounts already have one).',
    ],
    async prompts() {
      info(['Region: e.g. us-east-1, us-west-2, eu-west-1. Pick one near your users.']);
      const region = await ask('Region', { def: 'us-east-1' });
      info(['', 'Instance type: t3.small (2 GB RAM) is a solid start. Use t3.medium for more headroom.']);
      const instance_type = await ask('Instance type', { def: 't3.small' });
      info(['', 'SSH (optional): the name of an existing EC2 key pair lets you SSH in later.',
            'Leave blank to skip SSH access.']);
      const key_name = await ask('EC2 key pair name', {});
      return { region, instance_type, key_name };
    },
  },
  digitalocean: {
    label: 'DigitalOcean',
    menuDesc: 'Droplet · $12/mo · easiest (just an API token)',
    dir: 'terraform/digitalocean',
    credsLines: [
      'Before continuing, make sure you have:',
      '  • A DigitalOcean API token with write access. Create one at:',
      '      https://cloud.digitalocean.com/account/api/tokens',
    ],
    async prompts() {
      info(['Paste your DigitalOcean API token (it starts with dop_v1_).']);
      const do_token = await ask('DigitalOcean API token', { required: true, secret: true });
      info(['', 'Region: e.g. nyc1, sfo3, ams3, sgp1. Pick one near your users.']);
      const region = await ask('Region', { def: 'nyc1' });
      info(['', 'Droplet size: s-1vcpu-2gb (2 GB RAM) is a good start at $12/mo.']);
      const droplet_size = await ask('Droplet size', { def: 's-1vcpu-2gb' });
      info(['', 'SSH (optional): an SSH key fingerprint from your DO account enables SSH access.',
            'Find it under Settings → Security. Leave blank to skip.']);
      const fp = await ask('SSH key fingerprint', {});
      const out = { do_token, region, droplet_size };
      if (fp) out.ssh_key_fingerprints = [fp];
      return out;
    },
  },
};

// ── Deploy flow ──────────────────────────────────────────────────────────────
async function deploy(generateOnly) {
  banner();
  info([
    'This wizard provisions one small VM on your cloud and runs the full Enlight',
    'stack on it (app + database + queue + HTTPS proxy). It takes ~5–10 minutes.',
    'Everything you enter is saved locally; nothing is sent anywhere but your cloud.',
    'You can stop and re-run this command at any time to pick up where you left off.',
  ]);

  // ── Resume detection ──
  // If a previous run left config (or a partial/complete provision) behind, offer
  // to continue it instead of starting from scratch.
  const prev = generateOnly ? null : existingDeployment();
  if (prev) {
    const pdef = CLOUDS[prev.cloud];
    log();
    if (prev.provisioned) {
      ok(`Found an existing ${pdef?.label ?? prev.cloud} deployment.`);
      info(['Re-applying is safe and idempotent — use it to finish an interrupted run or push config changes.']);
    } else {
      ok(`Found a saved ${pdef?.label ?? prev.cloud} configuration that hasn\'t been provisioned yet.`);
      info(['You can finish provisioning it now without re-entering anything.']);
    }
    const choice = await select('What would you like to do?', [
      { label: prev.provisioned ? 'Resume / update this deployment' : 'Continue provisioning it', value: 'resume',
        desc: 'Re-run Terraform with the saved settings (recommended).' },
      { label: 'Start a new deployment', value: 'new',
        desc: 'Re-enter everything. Overwrites the saved config for that cloud.' },
      { label: 'Tear it down', value: 'destroy', desc: 'Destroy the cloud resources and remove state.' },
    ]);
    if (choice === 'resume') {
      await provision(pdef ?? { dir: prev.dir, label: prev.cloud }, readDomainFromEnv(prev.dir));
      return;
    }
    if (choice === 'destroy') {
      await destroy();
      return;
    }
    // 'new' → fall through to the fresh wizard below.
    log();
    warn('Starting a new deployment. The previous config for the chosen cloud will be overwritten.');
  }

  // ── Step 1: cloud ──
  section(1, 4, 'Choose your cloud');
  reqs([
    'An account with one of: Google Cloud, AWS, or DigitalOcean.',
    'Terraform — installed automatically later if you don\'t have it.',
  ]);
  info(['Enlight runs on a single VM. Pick where to create it.']);
  const cloud = await select('Cloud provider', [
    { label: CLOUDS.gcp.label, value: 'gcp', desc: CLOUDS.gcp.menuDesc },
    { label: CLOUDS.aws.label, value: 'aws', desc: CLOUDS.aws.menuDesc },
    { label: CLOUDS.digitalocean.label, value: 'digitalocean', desc: CLOUDS.digitalocean.menuDesc },
  ]);
  const def = CLOUDS[cloud];
  log();
  info(def.credsLines);

  log();
  info([
    'Source access: the server builds Enlight from its GitHub repo. If that repo is',
    'PRIVATE, paste a GitHub token (classic, with "repo" scope, or fine-grained with',
    'read access) so the server can clone it. Public repo? Just press Enter.',
    'Create one at https://github.com/settings/tokens',
  ]);
  const githubToken = await ask('GitHub access token (only if the app repo is private)', { secret: true });

  // ── Step 2: AI ──
  section(2, 4, 'AI configuration');
  reqs([
    'Optional: an API key for your AI platform (Anthropic or OpenAI) — or add it in-app later.',
    'Optional: an embeddings key (Voyage or OpenAI) for knowledge base search.',
  ]);
  info([
    'Enlight\'s agent uses a large language model to triage and answer tickets.',
    'Choose a platform now — you can change it any time in Settings → AI Keys.',
  ]);
  const aiProvider = await select('AI platform', [
    { label: 'Anthropic (Claude)', value: 'anthropic', desc: 'Recommended — the platform Enlight is built and tuned for.' },
    { label: 'OpenAI (GPT)', value: 'openai', desc: 'Use GPT-4o / GPT-4.1 models instead.' },
  ]);
  let anthropicKey = '', openaiKey = '';
  log();
  if (aiProvider === 'anthropic') {
    info(['Get a key at https://console.anthropic.com → API Keys.',
          'You can leave this blank and add it later in the app (the agent stays idle until then).']);
    anthropicKey = await ask('Anthropic API key', { secret: true });
  } else {
    info(['Get a key at https://platform.openai.com/api-keys.',
          'You can leave this blank and add it later in the app (the agent stays idle until then).']);
    openaiKey = await ask('OpenAI API key', { secret: true });
  }

  log();
  info(['Knowledge base search uses an embeddings provider (separate from the chat model above).']);
  const embeddingProvider = await select('Embeddings provider', [
    { label: 'Voyage AI', value: 'voyage', desc: 'Recommended — voyage-large-2, free tier at voyageai.com.' },
    { label: 'OpenAI', value: 'openai', desc: 'text-embedding-3-small — reuses your OpenAI key.' },
  ]);
  let voyageKey = '';
  log();
  if (embeddingProvider === 'voyage') {
    info(['Get a key at https://www.voyageai.com (free tier).',
          'Leave blank to skip knowledge base search for now — you can add it later.']);
    voyageKey = await ask('Voyage API key', { secret: true });
  } else if (!openaiKey) {
    info(['OpenAI embeddings need an OpenAI key (you didn\'t enter one above).']);
    openaiKey = await ask('OpenAI API key', { secret: true });
  }

  // ── Step 3: domain ──
  section(3, 4, 'Domain & HTTPS');
  reqs([
    'Optional: a domain name (or subdomain) you own.',
    'Optional: access to that domain\'s DNS to add an A record after provisioning.',
    'No domain? You can skip this and still deploy (plain HTTP).',
  ]);
  info([
    'If you have a domain, Enlight gets automatic HTTPS (Caddy + Let\'s Encrypt) — no certs to buy.',
    'After this finishes you\'ll point a DNS A record at the server\'s IP (shown at the end).',
    'A subdomain like  itsm.yourcompany.com  is recommended.',
    'Leave blank to serve plain HTTP on port 80 (you can add a domain later).',
  ]);
  const domain = await ask('Domain for this server', {});

  // ── Step 4: cloud settings ──
  section(4, 4, `${def.label} settings`);
  reqs([
    `Your ${def.label} credentials ready (the checklist shown after Step 1).`,
    'Region / size values — sensible defaults are provided, just press Enter to accept.',
  ]);
  const cloudVars = await def.prompts();
  log();

  // ── Generate secrets + write files ──
  const app = {
    aiProvider, embeddingProvider, anthropicKey, openaiKey, voyageKey, domain, githubToken,
    pgPassword: randPass(),
    jwtSecret: randHex(24),
    sessionSecret: randHex(24),
    encKey: randHex(32), // 64 hex chars = 32 bytes
  };
  const tfDir = path.join(__dirname, def.dir);
  fs.writeFileSync(path.join(tfDir, '.env'), buildEnv(app));
  fs.writeFileSync(path.join(tfDir, 'terraform.tfvars'), buildTfvars(cloudVars));
  ok(`Wrote ${def.dir}/.env and terraform.tfvars`);
  log(color('dim', '  Secrets were auto-generated. These files contain credentials — keep them private.'));
  log();

  saveState({ cloud, dir: def.dir });

  if (generateOnly) {
    ok('Generated config only (--generate-only). Run terraform yourself when ready:');
    info([`  terraform -chdir=${def.dir} init && terraform -chdir=${def.dir} apply`]);
    rl.close();
    return;
  }

  await provision(def, domain);
}

// ── Provision (shared by fresh deploys and resumes) ──────────────────────────
async function provision(def, domain) {
  // Make sure Terraform is available — offer to install it if not.
  let tf = resolveTerraform();
  if (tf) {
    TERRAFORM = tf;
  } else {
    warn('Terraform is required to provision, and it isn\'t installed.');
    const installNow = await confirm('Download and install Terraform now (official HashiCorp binary)?', true);
    if (installNow) {
      try {
        const v = await installTerraform();
        ok(`Terraform ${v} installed into ./bin.`);
        tf = TERRAFORM;
      } catch (e) {
        err(`Automatic install failed: ${e.message}`);
      }
    }
  }
  if (!tf) {
    warn('Config files are ready, but provisioning needs Terraform.');
    info([
      'Install it from https://developer.hashicorp.com/terraform/install, then run:',
      `  terraform -chdir=${def.dir} init && terraform -chdir=${def.dir} apply`,
    ]);
    rl.close();
    return;
  }

  const go = await confirm(`Provision now on ${def.label}? This creates/updates real cloud resources.`, true);
  if (!go) { warn('Skipped provisioning. Config files are saved — run again to resume.'); rl.close(); return; }
  rl.close();

  log();
  log(color('blue', '  → terraform init'));
  if (await runTf(def.dir, ['init', '-input=false']) !== 0) {
    err('terraform init failed. Fix the issue above and run `node deploy.mjs` again to resume.');
    process.exit(1);
  }

  log();
  log(color('blue', '  → terraform apply'));
  if (await runTf(def.dir, ['apply', '-input=false', '-auto-approve']) !== 0) {
    err('terraform apply failed.');
    info([
      'If the error above mentions auth / invalid_grant / reauth (GCP) or expired',
      'credentials, refresh them and resume:',
      '  • GCP:          gcloud auth application-default login',
      '  • AWS:          aws sso login   (or refresh your access keys)',
      '  • DigitalOcean: generate a new API token and re-run',
      'Then run `node deploy.mjs` again and choose Resume — it picks up where it stopped.',
    ]);
    process.exit(1);
  }

  // ── Show outputs ──
  log();
  const out = spawnSync(TERRAFORM, [`-chdir=${def.dir}`, 'output', '-json'], { encoding: 'utf8' });
  let ip = '';
  let httpUrl = '';
  try {
    const o = JSON.parse(out.stdout || '{}');
    ip = o.public_ip?.value ?? '';
    httpUrl = o.url?.value ?? '';
    log(color('green', color('bold', '  🎉 Deployed!')));
    if (ip)      log(`     Public IP : ${color('bold', ip)}`);
    if (domain)  log(`     URL       : ${color('bold', `https://${domain}`)} ${color('dim', '(after DNS + cert)')}`);
    else if (httpUrl) log(`     URL       : ${color('bold', httpUrl)}`);
    if (o.ssh)   log(`     SSH       : ${color('dim', o.ssh.value)}`);
  } catch { /* ignore */ }

  log();
  log(color('bold', '  Next steps'));
  if (domain) {
    log(`    1. Point an A record for ${color('bold', domain)} at ${color('bold', ip || 'the IP above')}.`);
    log(`    2. Wait ~3–5 min for the first build, then Caddy auto-issues a TLS cert.`);
    log(`    3. Open ${color('bold', `https://${domain}`)} — the setup wizard creates your org + admin.`);
  } else {
    log(`    1. Wait ~3–5 min for the first build to finish on the VM.`);
    log(`    2. Open ${httpUrl || 'the URL above'} — the setup wizard creates your org + admin.`);
    log(color('dim', `    3. To add HTTPS later: point a domain at the IP, then set SITE_ADDRESS (and`));
    log(color('dim', `       WEB_URL/API_URL) in /opt/enlight/.env and run \`docker compose up -d\`.`));
  }
  log();
  log(color('dim', `  Tear down later with:  node deploy.mjs destroy`));
  log();
}

// ── Destroy flow ─────────────────────────────────────────────────────────────
async function destroy() {
  banner();
  if (!fs.existsSync(STATE_FILE)) { err('No previous deployment found (.enlight-deploy.json missing).'); rl.close(); return; }
  const { cloud, dir } = JSON.parse(fs.readFileSync(STATE_FILE, 'utf8'));
  warn(`This will DESTROY the ${CLOUDS[cloud]?.label ?? cloud} deployment and all its data.`);
  const sure = await confirm('Are you sure?', false);
  rl.close();
  if (!sure) { log('  Cancelled.'); return; }
  const tf = resolveTerraform();
  if (!tf) { err('Terraform not found (system PATH or ./bin). Install it, then retry.'); return; }
  TERRAFORM = tf;
  if (await runTf(dir, ['init', '-input=false']) !== 0) { err('terraform init failed.'); return; }
  if (await runTf(dir, ['destroy', '-input=false', '-auto-approve']) !== 0) {
    err('terraform destroy failed (see above) — resources may still exist. Re-auth if needed and retry.');
    return;
  }
  ok('Destroyed.');
}

// ── Entry ────────────────────────────────────────────────────────────────────
const cmd = process.argv[2];
const generateOnly = process.argv.includes('--generate-only');
try {
  if (cmd === 'destroy') {
    await destroy();
  } else if (cmd === 'install-terraform') {
    // Standalone: install Terraform without deploying anything.
    const existing = resolveTerraform();
    if (existing && existing !== localTfPath()) {
      ok(`Terraform is already installed (${existing}).`);
    } else {
      const v = await installTerraform();
      ok(`Terraform ${v} installed into ./bin/terraform.`);
    }
    rl.close();
  } else {
    await deploy(generateOnly);
  }
} catch (e) {
  err(e?.message ?? String(e));
  process.exit(1);
}
